"""Simulation-level OSMOSE parameter definitions."""

from osmose.schema.base import OsmoseField, ParamType

SIMULATION_FIELDS: list[OsmoseField] = [
    OsmoseField(
        key_pattern="simulation.time.ndtperyear",
        param_type=ParamType.INT,
        default=24,
        min_val=1,
        max_val=365,
        description="Number of time steps per year",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="simulation.time.nyear",
        param_type=ParamType.INT,
        default=100,
        min_val=1,
        max_val=1000,
        description="Total simulation years",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="simulation.nspecies",
        param_type=ParamType.INT,
        default=3,
        min_val=1,
        max_val=50,
        description="Number of focal species",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="simulation.nresource",
        param_type=ParamType.INT,
        default=0,
        min_val=0,
        max_val=50,
        description="Number of resource/plankton groups",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="simulation.nbackground",
        param_type=ParamType.INT,
        default=0,
        min_val=0,
        max_val=50,
        description="Number of background species",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="simulation.nschool",
        param_type=ParamType.INT,
        default=20,
        min_val=1,
        max_val=200,
        description="Default number of schools per species",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="simulation.ncpu",
        param_type=ParamType.INT,
        default=1,
        min_val=1,
        max_val=128,
        description="Number of CPUs for parallel runs",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="simulation.nsimulation",
        param_type=ParamType.INT,
        default=1,
        min_val=1,
        max_val=1000,
        description="Number of replicate simulations",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="simulation.restart.file",
        param_type=ParamType.FILE_PATH,
        default="null",
        description="Path to restart file",
        category="simulation",
        required=False,
    ),
    OsmoseField(
        key_pattern="simulation.bioen.enabled",
        param_type=ParamType.BOOL,
        default=False,
        description="Enable bioenergetics module",
        category="simulation",
        advanced=True,
    ),
    OsmoseField(
        key_pattern="simulation.genetic.enabled",
        param_type=ParamType.BOOL,
        default=False,
        description="Enable genetic module",
        category="simulation",
        advanced=True,
    ),
    OsmoseField(
        key_pattern="simulation.incoming.flux.enabled",
        param_type=ParamType.BOOL,
        default=False,
        description="Enable incoming flux of organisms",
        category="simulation",
        advanced=True,
    ),
    OsmoseField(
        key_pattern="simulation.fishing.mortality.enabled",
        param_type=ParamType.BOOL,
        default=True,
        description="Enable fishing mortality",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="simulation.nfisheries",
        param_type=ParamType.INT,
        default=0,
        min_val=0,
        max_val=50,
        description="Number of fisheries",
        category="simulation",
    ),
    OsmoseField(
        key_pattern="mortality.subdt",
        param_type=ParamType.INT,
        default=10,
        min_val=1,
        max_val=100,
        description="Number of mortality sub-time-steps per main time step",
        category="simulation",
        advanced=True,
    ),
    OsmoseField(
        key_pattern="stochastic.mortality.randomseed.fixed",
        param_type=ParamType.BOOL,
        default=False,
        description="Fix random seed for stochastic mortality (reproducibility)",
        category="simulation",
        advanced=True,
    ),
]
