"""Per-species OSMOSE parameter definitions."""

from osmose.schema.base import OsmoseField, ParamType

SPECIES_FIELDS: list[OsmoseField] = [
    # ── Identity ──────────────────────────────────────────────────────────
    OsmoseField(
        key_pattern="species.name.sp{idx}",
        param_type=ParamType.STRING,
        default="",
        description="Species common or scientific name",
        category="identity",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.type.sp{idx}",
        param_type=ParamType.ENUM,
        default="focal",
        choices=["focal", "resource", "background"],
        description="Species type",
        category="identity",
        indexed=True,
    ),
    # ── Von Bertalanffy Growth ────────────────────────────────────────────
    OsmoseField(
        key_pattern="species.linf.sp{idx}",
        param_type=ParamType.FLOAT,
        default=100.0,
        min_val=1.0,
        max_val=1000.0,
        description="L-infinity (asymptotic length)",
        category="growth",
        unit="cm",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.k.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.2,
        min_val=0.01,
        max_val=3.0,
        description="Von Bertalanffy growth coefficient",
        category="growth",
        unit="year^-1",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.t0.sp{idx}",
        param_type=ParamType.FLOAT,
        default=-0.5,
        min_val=-10.0,
        max_val=0.0,
        description="Theoretical age at zero length",
        category="growth",
        unit="year",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.vonbertalanffy.threshold.age.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.0,
        min_val=0.0,
        max_val=50.0,
        description="Age threshold for switching growth models",
        category="growth",
        unit="year",
        indexed=True,
        advanced=True,
    ),
    OsmoseField(
        key_pattern="species.lmax.sp{idx}",
        param_type=ParamType.FLOAT,
        default=120.0,
        min_val=1.0,
        max_val=2000.0,
        description="Maximum observed body length",
        category="growth",
        unit="cm",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="growth.java.classname.sp{idx}",
        param_type=ParamType.ENUM,
        default="fr.ird.osmose.growth.VonBertalanffy",
        choices=[
            "fr.ird.osmose.growth.VonBertalanffy",
            "fr.ird.osmose.growth.Gompertz",
            "fr.ird.osmose.growth.Linear",
        ],
        description="Java class implementing the growth model",
        category="growth",
        indexed=True,
        advanced=True,
    ),
    # ── Length-Weight ─────────────────────────────────────────────────────
    OsmoseField(
        key_pattern="species.length2weight.condition.factor.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.01,
        min_val=0.0001,
        max_val=1.0,
        description="Length-weight condition factor (a in W = a * L^b)",
        category="growth",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.length2weight.allometric.power.sp{idx}",
        param_type=ParamType.FLOAT,
        default=3.0,
        min_val=2.0,
        max_val=4.0,
        description="Length-weight allometric power (b in W = a * L^b)",
        category="growth",
        indexed=True,
    ),
    # ── Reproduction ─────────────────────────────────────────────────────
    OsmoseField(
        key_pattern="species.egg.size.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.1,
        min_val=0.001,
        max_val=10.0,
        description="Egg size at hatching",
        category="reproduction",
        unit="cm",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.egg.weight.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.001,
        min_val=0.0001,
        max_val=100.0,
        description="Egg weight at hatching",
        category="reproduction",
        unit="g",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.maturity.size.sp{idx}",
        param_type=ParamType.FLOAT,
        default=50.0,
        min_val=0.1,
        max_val=1000.0,
        description="Size at sexual maturity",
        category="reproduction",
        unit="cm",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.maturity.age.sp{idx}",
        param_type=ParamType.FLOAT,
        default=3.0,
        min_val=0.0,
        max_val=100.0,
        description="Age at sexual maturity",
        category="reproduction",
        unit="year",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.relativefecundity.sp{idx}",
        param_type=ParamType.FLOAT,
        default=500.0,
        min_val=1.0,
        max_val=1e9,
        description="Number of eggs per gram of mature female body weight",
        category="reproduction",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.sexratio.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.5,
        min_val=0.0,
        max_val=1.0,
        description="Proportion of females in the population",
        category="reproduction",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="reproduction.season.file.sp{idx}",
        param_type=ParamType.FILE_PATH,
        default="",
        description="Path to CSV file defining seasonal reproduction pattern",
        category="reproduction",
        indexed=True,
        required=False,
    ),
    # ── Life History ─────────────────────────────────────────────────────
    OsmoseField(
        key_pattern="species.lifespan.sp{idx}",
        param_type=ParamType.FLOAT,
        default=10.0,
        min_val=0.5,
        max_val=200.0,
        description="Maximum lifespan",
        category="life_history",
        unit="year",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="species.first.feeding.age.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.0,
        min_val=0.0,
        max_val=10.0,
        description="Age at which larvae begin active feeding",
        category="life_history",
        unit="year",
        indexed=True,
        advanced=True,
    ),
    # ── Predation ────────────────────────────────────────────────────────
    OsmoseField(
        key_pattern="predation.ingestion.rate.max.sp{idx}",
        param_type=ParamType.FLOAT,
        default=3.5,
        min_val=0.1,
        max_val=100.0,
        description="Maximum ingestion rate",
        category="predation",
        unit="g/g/year",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="predation.efficiency.critical.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.57,
        min_val=0.0,
        max_val=1.0,
        description="Critical predation efficiency below which starvation occurs",
        category="predation",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="predation.predprey.sizeratio.max.sp{idx}",
        param_type=ParamType.FLOAT,
        default=3.5,
        min_val=1.0,
        max_val=1000.0,
        description="Maximum predator/prey size ratio",
        category="predation",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="predation.predprey.sizeratio.min.sp{idx}",
        param_type=ParamType.FLOAT,
        default=1.5,
        min_val=1.0,
        max_val=1000.0,
        description="Minimum predator/prey size ratio",
        category="predation",
        indexed=True,
    ),
    # ── Mortality ────────────────────────────────────────────────────────
    OsmoseField(
        key_pattern="mortality.natural.rate.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.2,
        min_val=0.0,
        max_val=10.0,
        description="Natural mortality rate (excluding predation and starvation)",
        category="mortality",
        unit="year^-1",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="mortality.natural.larva.rate.sp{idx}",
        param_type=ParamType.FLOAT,
        default=2.0,
        min_val=0.0,
        max_val=50.0,
        description="Additional natural mortality rate for larvae",
        category="mortality",
        unit="year^-1",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="mortality.starvation.rate.max.sp{idx}",
        param_type=ParamType.FLOAT,
        default=3.0,
        min_val=0.0,
        max_val=50.0,
        description="Maximum starvation mortality rate",
        category="mortality",
        unit="year^-1",
        indexed=True,
    ),
    # ── Fishing ──────────────────────────────────────────────────────────
    OsmoseField(
        key_pattern="mortality.fishing.rate.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.0,
        min_val=0.0,
        max_val=10.0,
        description="Annual fishing mortality rate",
        category="fishing",
        unit="year^-1",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="mortality.fishing.recruitment.age.sp{idx}",
        param_type=ParamType.FLOAT,
        default=1.0,
        min_val=0.0,
        max_val=100.0,
        description="Age at recruitment to the fishery",
        category="fishing",
        unit="year",
        indexed=True,
    ),
    OsmoseField(
        key_pattern="mortality.fishing.recruitment.size.sp{idx}",
        param_type=ParamType.FLOAT,
        default=0.0,
        min_val=0.0,
        max_val=1000.0,
        description="Size at recruitment to the fishery",
        category="fishing",
        unit="cm",
        indexed=True,
    ),
    # ── Initialization ───────────────────────────────────────────────────
    OsmoseField(
        key_pattern="population.seeding.biomass.sp{idx}",
        param_type=ParamType.FLOAT,
        default=1000.0,
        min_val=0.0,
        max_val=1e12,
        description="Initial seeding biomass for the population",
        category="initialization",
        unit="tons",
        indexed=True,
    ),
]
